# Generated by Django 5.1 on 2024-10-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                ("roomID", models.AutoField(primary_key=True, serialize=False)),
                ("roomName", models.CharField(max_length=100, null=True)),
                ("roomNumber", models.IntegerField(unique=True)),
                ("occupancy", models.IntegerField(default=0)),
                ("totalSeats", models.IntegerField()),
                ("roomType", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="seatMng",
            fields=[
                ("seatID", models.AutoField(primary_key=True, serialize=False)),
                ("priceRate", models.FloatField()),
                ("active", models.BooleanField(default=True)),
                ("RoomNumber", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="seatNumber",
            fields=[
                ("seatNumberPK", models.AutoField(primary_key=True, serialize=False)),
                ("seatNumber", models.CharField(max_length=25)),
                ("seatPriceRate", models.FloatField(default=0.0)),
                ("occupiedStatus", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "roomNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seatRoomNumber",
                        to="seatMng.rooms",
                    ),
                ),
            ],
        ),
    ]
