# Generated by Django 5.1 on 2024-08-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                ("roomID", models.AutoField(primary_key=True, serialize=False)),
                ("roomName", models.CharField(max_length=100)),
                ("roomNumber", models.IntegerField(unique=True)),
                ("occupancy", models.IntegerField(default=0)),
                ("totalSeats", models.IntegerField()),
                ("roomType", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="seatMng",
            fields=[
                ("seatID", models.AutoField(primary_key=True, serialize=False)),
                ("priceRate", models.FloatField()),
                ("active", models.BooleanField(default=True)),
                (
                    "roomID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seatRoom",
                        to="seatMng.rooms",
                    ),
                ),
            ],
        ),
    ]
