# Generated by Django 5.1 on 2024-10-03 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatmng",
            name="seatNumberPK",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="seatNumber_PK",
                to="seatMng.seatnumber",
            ),
            preserve_default=False,
        ),
    ]
