# Generated by Django 5.1 on 2024-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatmng",
            name="seatNumber",
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
