# Generated by Django 5.1 on 2024-08-29 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0002_seatmng_seatnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatmng",
            name="dateJoined",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 30, 1, 19, 27, 378922)
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="roomName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="seatmng",
            name="seatNumber",
            field=models.IntegerField(null=True),
        ),
    ]
