# Generated by Django 5.1 on 2024-11-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0002_seatmng_seatnumberpk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seatmng",
            old_name="seatNumberPK",
            new_name="seatNumber",
        ),
    ]
