# Generated by Django 5.1 on 2024-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0003_seatmng_datejoined_alter_rooms_roomname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seatmng",
            name="dateJoined",
        ),
        migrations.AlterField(
            model_name="seatmng",
            name="seatNumber",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
