# Generated by Django 5.1 on 2024-09-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0004_remove_seatmng_datejoined_alter_seatmng_seatnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatmng",
            name="seatNumber",
            field=models.IntegerField(),
        ),
    ]
