# Generated by Django 5.1 on 2024-09-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0005_alter_seatmng_seatnumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="seatNumber",
            fields=[
                ("seatNumber", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "roomNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seatRoomNumber",
                        to="seatMng.rooms",
                    ),
                ),
            ],
        ),
    ]
