# Generated by Django 5.1 on 2024-09-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0006_seatnumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seatmng",
            name="roomID",
        ),
        migrations.AlterField(
            model_name="seatmng",
            name="seatNumber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="seat_number",
                to="seatMng.seatnumber",
            ),
        ),
    ]
