# Generated by Django 5.1 on 2024-09-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0008_seatmng_userid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seatmng",
            name="userID",
        ),
    ]
