# Generated by Django 5.1 on 2024-09-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0009_remove_seatmng_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatmng",
            name="RoomNumber",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seatnumber",
            name="occupiedStatus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seatnumber",
            name="seatPriceRate",
            field=models.FloatField(default=0.0),
        ),
    ]
