# Generated by Django 5.1 on 2024-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0011_alter_seatmng_roomnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatnumber",
            name="seatNumber",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
