# Generated by Django 5.1 on 2024-09-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0012_alter_seatnumber_seatnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatnumber",
            name="seatNumber",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
