# Generated by Django 5.1 on 2024-08-30 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryList",
            fields=[
                ("categoryID", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=True)),
                ("type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("expenseID", models.AutoField(primary_key=True, serialize=False)),
                ("expenseTitle", models.CharField(max_length=50)),
                ("expenseAmount", models.FloatField()),
                ("description", models.TextField(null=True)),
                ("date", models.DateField(default=datetime.datetime.now)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                ("incomeID", models.AutoField(primary_key=True, serialize=False)),
                ("incomeCategory", models.CharField(max_length=50)),
                ("amount", models.FloatField(max_length=10)),
                ("discount", models.FloatField(max_length=10)),
                ("total", models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Vendors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("contactNumber", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("vendorType", models.CharField(max_length=20)),
            ],
        ),
    ]
