# Generated by Django 5.1 on 2024-10-03 09:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seatMng", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryList",
            fields=[
                ("categoryID", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=True)),
                ("type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("expenseID", models.AutoField(primary_key=True, serialize=False)),
                ("expenseTitle", models.CharField(max_length=50)),
                ("expenseAmount", models.FloatField()),
                ("description", models.TextField(null=True)),
                ("date", models.DateField(default=datetime.datetime.now)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="IncomingPayments",
            fields=[
                ("ipaymentID", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=datetime.date.today)),
                ("incomeCategory", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=100, null=True)),
                ("paidAmount", models.FloatField(default=0, max_length=10)),
                ("discountAmount", models.FloatField(default=0, max_length=10)),
                ("dueAmount", models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Vendors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("contactNumber", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("vendorType", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="BillGenerate",
            fields=[
                ("billID", models.AutoField(primary_key=True, serialize=False)),
                ("billedAmount", models.FloatField(default=0)),
                ("billedDate", models.DateField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Unpaid", "Unpaid"),
                            ("Partial", "Partial"),
                            ("Paid", "Paid"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                ("billedMonth", models.CharField(max_length=50)),
                ("billDescription", models.TextField(max_length=150, null=True)),
                ("discountAmount", models.FloatField(null=True)),
                (
                    "seatID_finance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seatID_Num",
                        to="seatMng.seatmng",
                    ),
                ),
            ],
        ),
    ]
