# Generated by Django 5.1 on 2024-09-01 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0002_income_paidby"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="date",
            field=models.DateField(default=datetime.datetime.now, verbose_name=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
