# Generated by Django 5.1 on 2024-11-19 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0003_rename_billeddate_billgenerate_transactiondate_and_more"),
        ("seatMng", "0002_seatmng_seatnumberpk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BillGenerate",
            new_name="TransactionTable",
        ),
    ]
