# Generated by Django 5.1 on 2024-09-01 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0004_alter_income_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="addedBy",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="added_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
