# Generated by Django 5.1 on 2024-11-26 15:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0004_rename_billgenerate_transactiontable"),
        ("seatMng", "0002_seatmng_seatnumberpk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactiontable",
            name="billDescription",
        ),
        migrations.RemoveField(
            model_name="transactiontable",
            name="billedAmount",
        ),
        migrations.RemoveField(
            model_name="transactiontable",
            name="billedMonth",
        ),
        migrations.RemoveField(
            model_name="transactiontable",
            name="discountAmount",
        ),
        migrations.RemoveField(
            model_name="transactiontable",
            name="seatID_finance",
        ),
        migrations.RemoveField(
            model_name="transactiontable",
            name="status",
        ),
        migrations.RemoveField(
            model_name="transactiontable",
            name="transactionDate",
        ),
        migrations.RemoveField(
            model_name="transactiontable",
            name="userID",
        ),
        migrations.AddField(
            model_name="transactiontable",
            name="addedBy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="addedBy",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactiontable",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="transactiontable",
            name="description",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactiontable",
            name="dueAmount",
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name="transactiontable",
            name="paidAmount",
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name="transactiontable",
            name="paidBy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="paidBy",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactiontable",
            name="tranxChannel",
            field=models.CharField(
                choices=[("CASH", "CASH"), ("BANK", "BANK"), ("ESEWA", "ESEWA")],
                default="CASH",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="transactiontable",
            name="tranxType",
            field=models.CharField(
                choices=[("INCOME", "INCOME"), ("EXPENSE", "EXPENSE")],
                default="INCOME",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BillGenerate",
            fields=[
                ("billID", models.AutoField(primary_key=True, serialize=False)),
                ("billedAmount", models.FloatField(default=0)),
                ("discountAmount", models.FloatField(null=True)),
                ("totalAmount", models.FloatField()),
                (
                    "paymentStatus",
                    models.CharField(
                        choices=[
                            ("Unpaid", "Unpaid"),
                            ("Partial", "Partial"),
                            ("Paid", "Paid"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                ("billedDate", models.DateField(default=datetime.datetime.now)),
                ("billedMonth", models.CharField(max_length=50)),
                ("billDescription", models.TextField(max_length=150, null=True)),
                (
                    "seatID_finance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seatID_Num",
                        to="seatMng.seatmng",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_bill",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transactiontable",
            name="billID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="billID_Transaction",
                to="financeMng.billgenerate",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="IncomingPayments",
        ),
    ]
