# Generated by Django 5.1 on 2024-09-01 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0005_income_addedby"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="description",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
