# Generated by Django 5.1 on 2024-09-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0007_billedpayment_incomingpayments_delete_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="billedpayment",
            name="billDescription",
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="billedpayment",
            name="billedMonth",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="billedpayment",
            name="discountAmount",
            field=models.FloatField(null=True),
        ),
    ]
