# Generated by Django 5.1 on 2024-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0008_billedpayment_billdescription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incomingpayments",
            name="paidUsing",
        ),
        migrations.AlterField(
            model_name="incomingpayments",
            name="discountAmount",
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name="incomingpayments",
            name="dueAmount",
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name="incomingpayments",
            name="paidAmount",
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
