# Generated by Django 5.1 on 2024-09-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0009_remove_incomingpayments_paidusing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billedpayment",
            name="billedAmount",
        ),
    ]
