# Generated by Django 5.1 on 2024-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0010_remove_billedpayment_billedamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="billedpayment",
            name="billedAmount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
