# Generated by Django 5.1 on 2024-10-02 16:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeMng", "0012_rename_seatid_billedpayment_seatid_finance_and_more"),
        ("seatMng", "0013_alter_seatnumber_seatnumber"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillGenerate",
            fields=[
                ("billID", models.AutoField(primary_key=True, serialize=False)),
                ("billedAmount", models.FloatField(default=0)),
                ("billedDate", models.DateField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Unpaid", "Unpaid"),
                            ("Partial", "Partial"),
                            ("Paid", "Paid"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                ("billedMonth", models.CharField(max_length=50)),
                ("billDescription", models.TextField(max_length=150, null=True)),
                ("discountAmount", models.FloatField(null=True)),
                (
                    "seatID_finance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seatID_Num",
                        to="seatMng.seatmng",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_bill",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BilledPayment",
        ),
    ]
