# Generated by Django 5.1 on 2024-09-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userMng", "0003_user_admissiondate_user_date_of_birth_user_seatid"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
