# Generated by Django 5.1 on 2024-09-13 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seatMng", "0009_remove_seatmng_userid"),
        ("userMng", "0007_remove_user_seatid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="seatID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seatID_Number",
                to="seatMng.seatmng",
            ),
            preserve_default=False,
        ),
    ]
